function [PriceFD, DeltaFD, GammaFD] = SpredbyEurope(Price1,Price2,num1,num2,Strike,Vol1,Vol2,Div1,Div2,Corr,Settle,Maturity,RiskFreeRate,OptSpec)
% RiskFreeRate = 0.03;
price1 = num1*Price1;
price2 = num2*Price2;
Compounding = -1;
Basis = 1;
RateSpec = intenvset('ValuationDate', Settle, 'StartDates', Settle, ...
    'EndDates', Maturity, 'Rates', RiskFreeRate, 'Compounding', ...
    Compounding, 'Basis', Basis);
StockSpec1 = stockspec(Vol1, price1, 'Continuous', Div1);
StockSpec2 = stockspec(Vol2, price2, 'Continuous', Div2);
OptSpec = 'call';
OutSpec = {'Price', 'Delta', 'Gamma'};
%% 计算欧式期权
% [PriceFD, DeltaFD, GammaFD]=...
%      spreadsensbybjs(RateSpec, StockSpec1, StockSpec2, Settle,Maturity, OptSpec, Strike, Corr, 'OutSpec', OutSpec)
% [PriceFD, DeltaFD, GammaFD] = ...
%     spreadsensbykirk(RateSpec, StockSpec1, StockSpec2, Settle,Maturity, OptSpec, Strike, Corr, 'OutSpec', OutSpec);
[PriceFD, DeltaFD, GammaFD, PriceGrid, AssetPrice1,AssetPrice2] = ...
    spreadsensbyfd(RateSpec, StockSpec1, StockSpec2, Settle, ...
    Maturity, OptSpec, Strike, Corr, 'OutSpec', OutSpec, ...    
    'PriceGridSize', [500 500], 'TimeGridSize', 100, ...
    'AssetPriceMin', [0 0], 'AssetPriceMax', [10e7 10e7], ...
    'AmericanOpt', 0); 
end